/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ECPrivateKey"
 * 	found in "ECPrivateKey.asn"
 * 	`asn1c -R`
 */

#include "jcp/internal/asn1_types/ECPrivateKey.h"

static int
memb_version_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value == 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_ECPrivateKey_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ECPrivateKey, version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		memb_version_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ECPrivateKey, privateKey),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"privateKey"
		},
	{ ATF_POINTER, 2, offsetof(struct ECPrivateKey, parameters),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ECParameters,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"parameters"
		},
	{ ATF_POINTER, 1, offsetof(struct ECPrivateKey, publicKey),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"publicKey"
		},
};
static const ber_tlv_tag_t asn_DEF_ECPrivateKey_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ECPrivateKey_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* version */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 }, /* privateKey */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 2, 0, 0 }, /* parameters */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 3, 0, 0 } /* publicKey */
};
static asn_SEQUENCE_specifics_t asn_SPC_ECPrivateKey_specs_1 = {
	sizeof(struct ECPrivateKey),
	offsetof(struct ECPrivateKey, _asn_ctx),
	asn_MAP_ECPrivateKey_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ECPrivateKey = {
	"ECPrivateKey",
	"ECPrivateKey",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ECPrivateKey_tags_1,
	sizeof(asn_DEF_ECPrivateKey_tags_1)
		/sizeof(asn_DEF_ECPrivateKey_tags_1[0]), /* 1 */
	asn_DEF_ECPrivateKey_tags_1,	/* Same as above */
	sizeof(asn_DEF_ECPrivateKey_tags_1)
		/sizeof(asn_DEF_ECPrivateKey_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ECPrivateKey_1,
	4,	/* Elements count */
	&asn_SPC_ECPrivateKey_specs_1	/* Additional specs */
};

