/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PrivateKeyInfo"
 * 	found in "privatekeyinfo.asn1"
 * 	`asn1c -R`
 */

#ifndef	_Attribute_H_
#define	_Attribute_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>
#include "AttributeSetValue.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Attribute */
typedef struct Attribute {
	OBJECT_IDENTIFIER_t	 type;
	AttributeSetValue_t	 values;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Attribute_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Attribute;

#ifdef __cplusplus
}
#endif

#endif	/* _Attribute_H_ */
#include <asn_internal.h>
