/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PrivateKeyInfo"
 * 	found in "privatekeyinfo.asn1"
 * 	`asn1c -R`
 */

#ifndef	_AttributeSetValue_H_
#define	_AttributeSetValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ANY.h>
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AttributeSetValue */
typedef struct AttributeSetValue {
	A_SET_OF(ANY_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AttributeSetValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AttributeSetValue;

#ifdef __cplusplus
}
#endif

#endif	/* _AttributeSetValue_H_ */
#include <asn_internal.h>
