/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PrivateKeyInfo"
 * 	found in "privatekeyinfo.asn1"
 * 	`asn1c -R`
 */

#ifndef	_EncryptedPrivateKeyInfo_H_
#define	_EncryptedPrivateKeyInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EncryptionAlgorithmIdentifier.h"
#include "EncryptedData.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EncryptedPrivateKeyInfo */
typedef struct EncryptedPrivateKeyInfo {
	EncryptionAlgorithmIdentifier_t	 encryptionAlgorithm;
	EncryptedData_t	 encryptedData;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EncryptedPrivateKeyInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EncryptedPrivateKeyInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _EncryptedPrivateKeyInfo_H_ */
#include <asn_internal.h>
