/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PrivateKeyInfo"
 * 	found in "privatekeyinfo.asn1"
 * 	`asn1c -R`
 */

#ifndef	_PrivateKeyInfo_H_
#define	_PrivateKeyInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Version.h"
#include "PrivateKeyAlgorithmIdentifier.h"
#include "PrivateKey.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Attributes;

/* PrivateKeyInfo */
typedef struct PrivateKeyInfo {
	Version_t	 version;
	PrivateKeyAlgorithmIdentifier_t	 privateKeyAlgorithm;
	PrivateKey_t	 privateKey;
	struct Attributes	*attributes	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PrivateKeyInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PrivateKeyInfo;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Attributes.h"

#endif	/* _PrivateKeyInfo_H_ */
#include <asn_internal.h>
